from enum import Enum


class CallState(str, Enum):
    CALL_STARTED = "CALL_STARTED"
    GREETING = "GREETING"
    INTENT_DETECTION = "INTENT_DETECTION"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    AUTHENTICATING = "AUTHENTICATING"
    AUTHENTICATED = "AUTHENTICATED"
    PROCESSING_REQUEST = "PROCESSING_REQUEST"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    COMPLETED = "COMPLETED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    HUMAN_HANDOFF = "HUMAN_HANDOFF"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    CALL_TERMINATED = "CALL_TERMINATED"


class CallEvent(str, Enum):
    START = "START"
    GREETED = "GREETED"
    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
    INTENT_NEEDS_AUTH = "INTENT_NEEDS_AUTH"
    INTENT_NO_AUTH_NEEDED = "INTENT_NO_AUTH_NEEDED"
    OTP_REQUESTED = "OTP_REQUESTED"
    OTP_VERIFIED = "OTP_VERIFIED"
    OTP_FAILED = "OTP_FAILED"
    OTP_EXHAUSTED = "OTP_EXHAUSTED"
    ACTION_REQUIRES_CONFIRMATION = "ACTION_REQUIRES_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    DECLINED = "DECLINED"
    ACTION_DONE = "ACTION_DONE"
    RESET_FOR_NEXT_TURN = "RESET_FOR_NEXT_TURN"
    HANDOFF_REQUESTED = "HANDOFF_REQUESTED"
    ERROR = "ERROR"
    CALL_ENDED = "CALL_ENDED"


# Global events are handled outside the table below: a customer can always ask
# for a human, and the system can always fail or hang up, regardless of state.
_GLOBAL_TRANSITIONS: dict[CallEvent, CallState] = {
    CallEvent.HANDOFF_REQUESTED: CallState.HUMAN_HANDOFF,
    CallEvent.ERROR: CallState.SYSTEM_ERROR,
    CallEvent.CALL_ENDED: CallState.CALL_TERMINATED,
}

_TRANSITIONS: dict[tuple[CallState, CallEvent], CallState] = {
    (CallState.CALL_STARTED, CallEvent.START): CallState.GREETING,
    (CallState.GREETING, CallEvent.GREETED): CallState.INTENT_DETECTION,
    (CallState.INTENT_DETECTION, CallEvent.INTENT_NEEDS_AUTH): CallState.AUTHENTICATION_REQUIRED,
    (CallState.INTENT_DETECTION, CallEvent.INTENT_NO_AUTH_NEEDED): CallState.PROCESSING_REQUEST,
    (CallState.AUTHENTICATION_REQUIRED, CallEvent.OTP_REQUESTED): CallState.AUTHENTICATING,
    (CallState.AUTHENTICATING, CallEvent.OTP_VERIFIED): CallState.AUTHENTICATED,
    (CallState.AUTHENTICATING, CallEvent.OTP_FAILED): CallState.AUTHENTICATING,
    (CallState.AUTHENTICATING, CallEvent.OTP_EXHAUSTED): CallState.AUTHENTICATION_FAILED,
    (CallState.AUTHENTICATED, CallEvent.MESSAGE_RECEIVED): CallState.PROCESSING_REQUEST,
    (CallState.PROCESSING_REQUEST, CallEvent.INTENT_NEEDS_AUTH): CallState.AUTHENTICATION_REQUIRED,
    (CallState.PROCESSING_REQUEST, CallEvent.ACTION_REQUIRES_CONFIRMATION): CallState.AWAITING_CONFIRMATION,
    (CallState.PROCESSING_REQUEST, CallEvent.ACTION_DONE): CallState.COMPLETED,
    (CallState.AWAITING_CONFIRMATION, CallEvent.CONFIRMED): CallState.PROCESSING_REQUEST,
    (CallState.AWAITING_CONFIRMATION, CallEvent.DECLINED): CallState.COMPLETED,
    (CallState.COMPLETED, CallEvent.RESET_FOR_NEXT_TURN): CallState.INTENT_DETECTION,
    (CallState.AUTHENTICATION_FAILED, CallEvent.RESET_FOR_NEXT_TURN): CallState.INTENT_DETECTION,
}


def next_state(current: CallState, event: CallEvent) -> CallState:
    if event in _GLOBAL_TRANSITIONS:
        return _GLOBAL_TRANSITIONS[event]
    try:
        return _TRANSITIONS[(current, event)]
    except KeyError:
        raise ValueError(f"No transition defined for state={current} event={event}")
